GET http://localhost:3001/api/persons/
###
GET http://localhost:3001/api/persons/6482f1b93cf96dc1ccec1bef
###
GET http://localhost:3001/api/persons/6482f1b93cf96dc1ccec1bee
###
GET http://localhost:3001/api/persons/6
###
GET http://localhost:3001/info
###
GET http://localhost:3001/unexistingEndpoint
###
DELETE http://localhost:3001/api/persons/2
###
POST http://localhost:3001/api/persons/ HTTP/1.1
Content-Type: application/json

{
    "name": "oh yea"
}
###
POST http://localhost:3005/api/persons/ HTTP/1.1
Content-Type: application/json

{
    "name": "oh yea",
    "number": "3333"
}
###
PUT http://localhost:3001/api/persons/6482f1b93cf96dc1ccec1bef
Content-Type: application/json

{
    "name": "oh yea",
    "number": "3333"
}